## E-commerce sales analyze

#### Import libraries

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

### Load Data

In [3]:
df_customer = pd.read_csv("customers_raw.csv")
df_order = pd.read_csv("orders_raw.csv")
df_product = pd.read_csv("products_raw.csv")
df_region = pd.read_csv("regions_raw.csv")

#### Show Data

In [6]:
# customer raw data
df_customer.head()

  customer_id customer_name  gender  age customer_segment signup_date
0      C00001    Customer 1  Female   33        Corporate    9/4/2024
1      C00002    Customer 2    Male   58         Consumer    6/8/2024
2      C00003    Customer 3  Female   19         Consumer   1/14/2025
3      C00004    Customer 4  Female   39        Corporate   4/28/2025
4      C00005    Customer 5    Male   56         Consumer    7/9/2024

In [7]:
# orders raw data
df_order.head()

,order_id,order_date,customer_id,product_id,region_id,quantity,discount,sales_amount,cost_amount,profit
0,O000001,8/20/2025 0:00,C00053,P0013,R014,3,0.00,970.29,789.78,180.51
1,O000002,5/29/2024 0:00,C00420,P0030,R015,2,0.00,968.74,640.56,328.18
2,O000003,11/15/2025 0:00,C01083,P0033,R006,2,0.00,1418.78,976.82,441.96
3,O000004,12/31/2024 0:00,C00119,P0043,R015,2,0.05,39.14,29.64,9.50
4,O000005,9/8/2025 0:00,C00455,P0096,R009,1,0.00,778.97,459.15,319.82

In [8]:
# product raw data
df_product.head()

,product_id,product_name,category,sub_category,cost,selling_price
0,P0001,Stationery Product 1,Furniture,Stationery,115.78,163.24
1,P0002,Paper Product 2,electronics,Paper,64.25,87.97
2,P0003,Cookware Product 3,Home & Kitchen,Cookware,770.19,1193.82
3,P0004,Accessories Product 4,Electronics,Accessories,686.46,1026.06
4,P0005,Men Product 5,Clothing,Men,567.23,672.19

In [9]:
# Region raw data
df_region.head()

  region_id           state                 city   region
0      R001     Maharashtra     Maharashtra City     West
1      R002         Gujarat         Gujarat City     West
2      R003       Rajasthan       Rajasthan City     West
3      R004             Goa             Goa City     West
4      R005  Madhya Pradesh  Madhya Pradesh City  Central

### Shape of Size

In [15]:
print("Shape of customer :",df_customer.shape)
print("Shape of orders :", df_order.shape)
print("Shape of product :", df_product.shape)
print("Shape of region :", df_region.shape)

Shape of customer : (2010, 6)
Shape of orders : (25050, 10)
Shape of product : (100, 6)
Shape of region : (20, 4)

### check information

In [19]:
print("Information of customer")
print(df_customer.info())

print("Information of Orders")
print(df_order.info())

Information of customer
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2010 entries, 0 to 2009
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customer_id       2010 non-null   object
 1   customer_name     2010 non-null   object
 2   gender            2010 non-null   object
 3   age               2010 non-null   int64
 4   customer_segment  2010 non-null   object
 5   signup_date       2010 non-null   object
dtypes: int64(1), object(5)
memory usage: 94.3+ KB
None
Information of Orders
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25050 entries, 0 to 25049
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   order_id      25050 non-null  object
 1   order_date    25050 non-null  object
 2   customer_id   24990 non-null  object
 3   product_id    25015 non-null  object
 4   region_id     25050 non-null  object
 5   quantity      25050 non-null  int64
 6   discount      25050 non-null  float64
 7   sales_amount  25050 non-null  float64
 8   cost_amount   25050 non-null  float64
 9   profit        25050 non-null  float64
dtypes: float64(4), int64(1), object(5)
memory usage: 1.9+ MB
None

## check and duplicate value

In [34]:
print("Remove customers duplicate value")
print(df_customer.duplicated())
print(df_customer.drop_duplicates(inplace=True))

Remove customers duplicate value
0       False
1       False
2       False
3       False
4       False
        ...
2005     True
2006     True
2007     True
2008     True
2009     True
Length: 2010, dtype: bool
None

In [37]:
print("Remove Orders Duplicates Value")
print(df_order.duplicated())
print(df_order.drop_duplicates(inplace=True))

Remove Orders Duplicates Value
0        False
1        False
2        False
3        False
4        False
         ...
25045     True
25046     True
25047     True
25048     True
25049     True
Length: 25050, dtype: bool
None

### After removing duplicate value shape of size

In [39]:
print("Shape of customer :",df_customer.shape)
print("Shape of orders :", df_order.shape)

Shape of customer : (2000, 6)
Shape of orders : (25000, 10)

### Check Data Type

In [45]:
print("Check Data Type of Customer Raw Data")
print(df_customer.dtypes)
print("Check Data Type of Order Raw Date")
print(df_order.dtypes)

Check Data Type of Customer Raw Data
customer_id         object
customer_name       object
gender              object
age                  int64
customer_segment    object
signup_date         object
dtype: object
Check Data Type of Order Raw Date
order_id         object
order_date       object
customer_id      object
product_id       object
region_id        object
quantity          int64
discount        float64
sales_amount    float64
cost_amount     float64
profit          float64
dtype: object

In [48]:
# convert sign_date into date format
df_customer["signup_date"] = pd.to_datetime(
        df_customer["signup_date"], 
        errors= "coerce")

In [50]:
# conert order_date into date format
df_order["order_date"] = pd.to_datetime(
    df_order["order_date"],
    errors= "coerce"
)

In [52]:
print(df_customer["signup_date"].dtype)
print(df_order["order_date"].dtype)

datetime64[ns]
datetime64[ns]

### check missing value

In [25]:
print(df_customer.isnull().sum())

customer_id         0
customer_name       0
gender              0
age                 0
customer_segment    0
signup_date         0
dtype: int64

In [26]:
print(df_order.isnull().sum())

order_id         0
order_date       0
customer_id     60
product_id      35
region_id        0
quantity         0
discount         0
sales_amount     0
cost_amount      0
profit           0
dtype: int64

In [70]:
# filling customer_id null value with Unknown
df_order["customer_id"] = df_order["customer_id"].fillna("Unknown")

In [71]:
# fill product_id null value replace with Unknown
df_order["product_id"] = df_order["product_id"].fillna("Unknown")

In [72]:
print(df_order.isnull().sum())

order_id         0
order_date      10
customer_id      0
product_id       0
region_id        0
quantity         0
discount         0
sales_amount     0
cost_amount      0
profit           0
dtype: int64

### Handle order date missing date

In [73]:
df_order[df_order["order_date"].isnull()]

,order_id,order_date,customer_id,product_id,region_id,quantity,discount,sales_amount,cost_amount,profit
1394,O001395,NaT,C00105,P0083,R009,2,0.00,2496.04,1735.06,760.98
2161,O002162,NaT,C00234,P0028,R017,2,0.05,1154.90,1039.42,115.48
5546,O005547,NaT,C01362,P0047,R011,2,0.05,937.25,812.16,125.09
6687,O006688,NaT,C00481,P0058,R004,2,0.05,907.72,718.12,189.60
8391,O008392,NaT,C00787,P0033,R018,1,0.00,709.39,488.41,220.98
9515,O009516,NaT,C00610,P0004,R008,1,0.00,1026.06,686.46,339.60
10788,O010789,NaT,C00896,P0068,R014,1,0.00,615.54,507.33,108.21
11294,O011295,NaT,C01933,P0070,R012,2,0.00,121.18,75.88,45.30
12415,O012416,NaT,C01709,P0086,R014,1,0.00,695.92,589.29,106.63
18413,O018414,NaT,C01371,P0097,R019,1,0.05,1148.41,802.79,345.62

In [90]:
df_order["order_date_status"] = df_order["order_date"].isna().map({
    True: "Missing",
    False: "Valid"
})

In [98]:
print(df_order[["order_id", "order_date", "order_date_status"]].head())

  order_id order_date order_date_status
0  O000001 2025-08-20             Valid
1  O000002 2024-05-29             Valid
2  O000003 2025-11-15             Valid
3  O000004 2024-12-31             Valid
4  O000005 2025-09-08             Valid

### Check Outlier Value

In [80]:
# for df_customers
df_customer.describe()

             age                 signup_date
count  2000.0000                        2000
mean     41.2350  2025-01-01 15:10:04.800000
min      18.0000         2024-01-01 00:00:00
25%      30.0000         2024-07-08 00:00:00
50%      41.0000         2025-01-09 00:00:00
75%      53.0000         2025-06-30 00:00:00
max      65.0000         2025-12-30 00:00:00
std      13.8247                         NaN

In [81]:
# for orders table
df_order.describe()

,order_date,quantity,discount,sales_amount,cost_amount,profit
count,24990,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000
mean,2024-12-31 04:29:50.924369664,1.922560,0.053530,1179.807450,910.504194,270.358958
min,2024-01-01 00:00:00,-5.000000,0.000000,-2900.280000,14.820000,-1110.800000
25%,2024-07-01 00:00:00,1.000000,0.000000,444.120000,340.640000,67.080000
50%,2025-01-01 00:00:00,2.000000,0.050000,881.680000,718.120000,165.250000
75%,2025-07-01 00:00:00,2.000000,0.100000,1602.860000,1258.200000,346.570000
max,2025-12-31 00:00:00,5.000000,0.200000,7286.350000,4485.150000,3014.300000
std,NaN,1.126114,0.056829,1065.145612,803.054932,323.448235

### Check columns name

In [89]:
print(df_customer.columns)
print(df_order.columns)
print(df_product.columns)
print(df_region.columns)

Index(['customer_id', 'customer_name', 'gender', 'age', 'customer_segment',
       'signup_date'],
      dtype='object')
Index(['order_id', 'order_date', 'customer_id', 'product_id', 'region_id',
       'quantity', 'discount', 'sales_amount', 'cost_amount', 'profit'],
      dtype='object')
Index(['product_id', 'product_name', 'category', 'sub_category', 'cost',
       'selling_price'],
      dtype='object')
Index(['region_id', 'state', 'city', 'region'], dtype='object')

### Add Column Transaction Type

In [106]:
df_order[df_order["quantity"] <= 0]

,order_id,order_date,customer_id,product_id,region_id,quantity,discount,sales_amount,cost_amount,profit,order_date_status
2948,O002949,2024-08-13,C00649,P0043,R003,-2,0.00,-41.20,29.64,-11.56,Valid
4296,O004297,2024-08-04,C00751,P0083,R018,-2,0.00,-2496.04,1735.06,-760.98,Valid
6734,O006735,2025-11-26,C00135,P0086,R005,-2,0.15,-1183.06,1178.58,-4.48,Valid
6832,O006833,2024-06-24,C01795,P0079,R014,-2,0.10,-183.47,153.66,-29.81,Valid
9330,O009331,2025-05-24,C01627,P0100,R004,-5,0.00,-2186.35,1290.95,-895.40,Valid
10256,O010257,2024-07-07,C01404,P0093,R010,-1,0.00,-907.16,594.21,-312.95,Valid
11309,O011310,2025-09-09,C01455,P0044,R002,-2,0.05,-734.62,531.74,-202.88,Valid
15666,O015667,2025-02-01,C01759,P0094,R007,-3,0.00,-2608.26,2085.24,-523.02,Valid
17015,O017016,2024-01-05,C00012,P0087,R007,-1,0.10,-334.41,228.34,-106.07,Valid
19474,O019475,2024-08-04,C00771,P0055,R011,-1,0.10,-760.79,517.78,-243.01,Valid
20803,O020804,2024-02-27,C01991,P0079,R015,-2,0.10,-183.47,153.66,-29.81,Valid
21471,O021472,2025-07-04,C00470,P0012,R014,-2,0.00,-2900.28,1789.48,-1110.80,Valid
22560,O022561,2024-03-12,C00124,P0051,R012,-1,0.05,-801.43,651.66,-149.77,Valid
24720,O024721,2024-04-10,C00478,P0086,R016,-3,0.00,-2087.76,1767.87,-319.89,Valid
24832,O024833,2024-12-09,C01771,P0033,R020,-1,0.00,-709.39,488.41,-220.98,Valid

In [114]:
# create a derived column
df_order["transaction_type"] = df_order["quantity"].apply(
    lambda x: "Return" if x < 0 else "Sale"
)

In [115]:
print(df_order["transaction_type"].value_counts())

transaction_type
Sale      24985
Return       15
Name: count, dtype: int64

In [119]:
print("Duplicate Product IDs:",
      df_product["product_id"].duplicated().sum())

Duplicate Product IDs: 0

In [120]:
print("Duplicate Region IDs:",
      df_region["region_id"].duplicated().sum())

Duplicate Region IDs: 0

In [121]:
print("Duplicate Customer IDs:",
      df_customer["customer_id"].duplicated().sum())

Duplicate Customer IDs: 0

### Text / Category Cleaning

In [122]:
print(df_product["category"].unique())

['Furniture ' 'electronics' 'Home & Kitchen' 'Electronics' 'Clothing'
 'Office Supplies' 'Furniture' 'OFFICE SUPPLIES']

In [123]:
df_product["category"] = df_product["category"].str.strip().str.title()

In [124]:
# after cleaning
print(df_product["category"].unique())

['Furniture' 'Electronics' 'Home & Kitchen' 'Clothing' 'Office Supplies']

In [ ]:
# for sub category

In [125]:
print(df_product["sub_category"].unique())

['Stationery' 'Paper' 'Cookware' 'Accessories' 'Men' 'Appliances'
 'Printers' 'Chairs' 'Women' 'Decor' 'Mobiles' 'Tables' 'Laptops' 'Kids'
 'Storage']

In [126]:
df_product["sub_category"] = df_product["sub_category"].str.strip().str.title()

In [127]:
print(df_product["sub_category"].unique())

['Stationery' 'Paper' 'Cookware' 'Accessories' 'Men' 'Appliances'
 'Printers' 'Chairs' 'Women' 'Decor' 'Mobiles' 'Tables' 'Laptops' 'Kids'
 'Storage']

In [128]:
# for gender
print(df_customer["gender"].unique())

['Female' 'Male' 'Other']

In [129]:
# for segment
print(df_customer["customer_segment"].unique())

['Corporate' 'Consumer' 'Small Business']

In [130]:
df_order[
    (df_order["quantity"] == 0) &
    (df_order["sales_amount"] != 0)
]

Empty DataFrame
Columns: [order_id, order_date, customer_id, product_id, region_id, quantity, discount, sales_amount, cost_amount, profit, order_date_status, transaction_type]
Index: []

### Final Data Quality Check + Cleaned Data Export

In [133]:
print(df_customer.shape)
print(df_order.shape)

(2000, 6)
(25000, 12)

In [136]:
print("Row :", df_order.shape[0])
print("Columns :", df_order.shape[1])

Row : 25000
Columns : 12

In [137]:
# missing value check
print(df_order.isnull().sum())

order_id              0
order_date           10
customer_id           0
product_id            0
region_id             0
quantity              0
discount              0
sales_amount          0
cost_amount           0
profit                0
order_date_status     0
transaction_type      0
dtype: int64

In [140]:
# duplicate value check
print("For Customer")
print(df_customer.duplicated().sum())
print("For Orders")
print(df_order.duplicated().sum())

For Customer
0
For Orders
0

In [142]:
# check data type
print(df_order.dtypes)

order_id                     object
order_date           datetime64[ns]
customer_id                  object
product_id                   object
region_id                    object
quantity                      int64
discount                    float64
sales_amount                float64
cost_amount                 float64
profit                      float64
order_date_status            object
transaction_type             object
dtype: object

In [143]:
# Transaction type check
print(df_order["transaction_type"].value_counts())

transaction_type
Sale      24985
Return       15
Name: count, dtype: int64

In [144]:
df_order.head()

,order_id,order_date,customer_id,product_id,region_id,quantity,discount,sales_amount,cost_amount,profit,order_date_status,transaction_type
0,O000001,2025-08-20,C00053,P0013,R014,3,0.00,970.29,789.78,180.51,Valid,Sale
1,O000002,2024-05-29,C00420,P0030,R015,2,0.00,968.74,640.56,328.18,Valid,Sale
2,O000003,2025-11-15,C01083,P0033,R006,2,0.00,1418.78,976.82,441.96,Valid,Sale
3,O000004,2024-12-31,C00119,P0043,R015,2,0.05,39.14,29.64,9.50,Valid,Sale
4,O000005,2025-09-08,C00455,P0096,R009,1,0.00,778.97,459.15,319.82,Valid,Sale

In [145]:
df_order.info()

<class 'pandas.core.frame.DataFrame'>
Index: 25000 entries, 0 to 24999
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   order_id           25000 non-null  object
 1   order_date         24990 non-null  datetime64[ns]
 2   customer_id        25000 non-null  object
 3   product_id         25000 non-null  object
 4   region_id          25000 non-null  object
 5   quantity           25000 non-null  int64
 6   discount           25000 non-null  float64
 7   sales_amount       25000 non-null  float64
 8   cost_amount        25000 non-null  float64
 9   profit             25000 non-null  float64
 10  order_date_status  25000 non-null  object
 11  transaction_type   25000 non-null  object
dtypes: datetime64[ns](1), float64(4), int64(1), object(6)
memory usage: 2.5+ MB

## Cleaned data Export

In [146]:
df_customer.to_csv("customer_cleaned.csv", index=False)

In [147]:
df_order.to_csv("order_cleaned.csv", index=False)

In [150]:
df_product.to_csv("product_cleaned.csv", index=False)

In [151]:
df_region.to_csv("region_cleaned.csv", index=False)

## cleaned file into SQL

In [152]:
from sqlalchemy import create_engine
engine = create_engine(
    "mysql+pymysql://root:atif@localhost/sales"
)

In [153]:
df_customer.to_sql(
    "customers",
    con=engine,
    if_exists="replace",
    index=False,
    chunksize=10000
)

2000

In [157]:
df_order.to_sql(
    "orders",
    con=engine,
    if_exists="replace",
    index=False,
    chunksize=10000
)

25000

In [155]:
df_product.to_sql(
    "product",
    con=engine,
    if_exists="replace",
    index=False,
    chunksize=10000
)

100

In [156]:
df_region.to_sql(
    "region",
    con=engine,
    if_exists="replace",
    index=False,
    chunksize=10000
)

20